### ISSUE TITLE
not possible to decouple from GH-Pages ?

### ISSUE THREAD

**Issue by jordila** [EthanMcBloxxer/jekyll-theme-mastodon#3]
Thanks for ...
i added

```
remote_theme: EthanMcBloxxer/jekyll-theme-mastodon@main
plugins:
```

to _config.yaml but updated  Gemfile too...

Still, no joy ... ,i cannot build locally.
Question , is not possible to decouple from GH-Pages with simple 'git clone' ?

(Congratuations, for this inspiring project... BTW )

**Comment by EthanMcBloxxer** [comment]
It's been a while since I worked on this project (and Ruby), so this might be bad practice or similar, but removing the `gemspec` line from the Gemfile in `remote` and changing the `baseurl` property of `_config.yml` to `/` (if necessary) should make it work.
Additionally, check if installing the `github-pages` gem is required. I'm not sure.

**Comment by jordila** [comment]
Fixed, thanks !
